import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer'
import Header from '@/components/header'
import { Separator } from '@/components/ui/separator'
import Breadcrumbs from '@/components/breadcrumb'
import { AppProvider } from '@/context/AppContext'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Neo Store',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
                <AppProvider>
                    <div className='px-[135px]'>
                        <Header />
                    </div>
                    <div className='mt-[96px]'/>
                    <Breadcrumbs />
                    <div className='px-[135px]'>{children}</div>
                    <Footer />
                </AppProvider>
            </body>
        </html>
    )
}
