import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer'
import Header from '@/components/header'
import { Separator } from '@/components/ui/separator'
import Breadcrumbs from '@/components/navigation/breadcrumb'
import { AppProvider } from '@/context/AppContext'
import { OrderProvider } from '@/context/OrderContext'
import React from 'react'
import Loading2 from '@/components/ui/loading2'
import MobileNav from '@/components/navigation/mobile-nav'
import { Toaster } from 'sonner'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Neo Store',
    description: 'Generated by create next app'
    // viewport: "width=device-width, initial-scale=1, maximum-scale=1",
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
                <AppProvider>
                    <Header />
                    <div className='mt-36' />
                    <Breadcrumbs />
                    <OrderProvider>
                        <React.Suspense
                            fallback={
                                <div className='w-full min-h-[400px] flex items-center justify-center'>
                                    <Loading2 />
                                </div>
                            }
                        >
                            <div className='2xl:px-[200px] xl:px-16 md:px-10 px-4'>
                                {children} <Toaster position='top-right' richColors/>
                            </div>
                        </React.Suspense>
                    </OrderProvider>
                    <Footer />
                    <MobileNav />
                </AppProvider>
            </body>
        </html>
    )
}
